name: ❓ Question
description: Ask a question
title: '[QUESTION] <title>'
labels: ['type: discussion']
body:
  - type: textarea
    attributes:
      label: Question
      description: What would you like to know? If you encounter unusual behavior or identified a missing feature, consider opening a bug report instead.
    validations:
      required: true
