/**
 * `@dxfrontier/cds-ts-repository` — typed data-access layer for SAP CAP TypeScript projects.
 *
 * Mental model:
 * - `BaseRepository<T>` wraps CDS-QL (`SELECT` / `INSERT` / `UPDATE` / `UPSERT` / `DELETE`) with typed
 *   methods for one CAP entity; `T` is a cds-typer singular type — plural types are accepted and
 *   narrowed via `ExtractSingular`.
 * - `BaseRepositoryDraft<T>` exposes the same operations against the draft table of a draft-enabled
 *   entity; combine both with `class X extends Mixin(BaseRepository<T>, BaseRepositoryDraft<T>)`.
 * - `repository.builder()` opens the chainable query API (`FindBuilder` / `FindOneBuilder`);
 *   `Filter<T>` builds typed where-trees accepted by most methods in place of a plain keys object.
 * - `@ExternalService('NAME')` reroutes every method to a remote OData service connected via
 *   `cds.connect.to('NAME')`; methods that cannot run remotely say so in their `@remarks`.
 *
 * Setup contract: peer dependency `@sap/cds` ^9 or ^10, Node.js >= 22, entity types generated by
 * cds-typer.
 *
 * Escape convention used in examples: a decorator shown at line start inside an example is written
 * with a leading slash — drop the leading slash when copying.
 *
 * Full docs ship with this package: node_modules/@dxfrontier/cds-ts-repository/README.md
 *
 * @example
 * ```ts
 * import { BaseRepository } from '@dxfrontier/cds-ts-repository';
 * import { Books } from '#cds-models/CatalogService';
 *
 * class BookRepository extends BaseRepository<Books> {
 *   constructor() {
 *     super(Books);
 *   }
 * }
 * ```
 *
 * @packageDocumentation
 */

export * from './core/BaseRepository';
export * from './core/BaseRepositoryDraft';
export * from './decorators/class';

export * from './util/filter/Filter';

export type * from './types/types';

export { Mixin } from 'ts-mixer';
