import type { QueryAPI, Request } from '@sap/cds';

import type { LanguageCode } from 'iso-639-1';

import type FindBuilder from '../util/find/FindBuilder';
import type { Filter } from '../util/filter/Filter';
import type FindOneBuilder from '../util/find/FindOneBuilder';

import type { Service } from '@sap/cds';

type ExternalServiceProps = {
  entities: Service['entities'];
  run: QueryAPI['run'];
};

type BaseRepositoryConstructor = {
  new (...args: any[]): unknown;
  externalService?: ExternalServiceProps;
};

/**
 * This ExtractSingular type is being used in `BaseRepository & BaseRepositoryDraft` to take the singular object `Entity` instead of the Array<object> generated by the `cds-typer`
 */
type ExtractSingular<T> = T extends any[] ? T[number] : T;

type Entity = { name: string } & Partial<{
  elements: unknown;
  drafts: { name: string };
}>;

type Entry<T> = Partial<T>;
type Entries<T> = Entry<T> | Entry<T>[];

type Draft<T> = EntryDraft<ExtractSingular<T>>;

type EntryDraft<T> = T & DraftAdministrativeFields;
type DraftEntries<T> = EntryDraft<T> | EntryDraft<T>[];

type DraftAdministrativeFields = {
  IsActiveEntity?: boolean | null;
  HasActiveEntity?: boolean | null;
  HasDraftEntity?: boolean | null;
  DraftAdministrativeData_DraftUUID?: string | null;
};

type AssociationFunction = (...args: unknown[]) => unknown;

type InsertResult<T> = {
  query: {
    INSERT: {
      entries: T[];
    };
  };
};

type LooseAutocomplete<T extends string> = T | Omit<string, T>;
type Locale = {
  locale: LooseAutocomplete<LanguageCode>;
};

type Columns<T> = keyof T | (keyof T)[];
type ShowOnlyColumns<T, K> = K extends (keyof T)[] ? K[number] : K extends keyof T ? K : never;

type FindReturn<T> = {
  /**
   * Get all entries from the table.
   * @returns FindBuilder
   * @example const results = await this.builder().find().execute()
   *
   * */
  find(): FindBuilder<T, string>;

  /**
   * Finds entries based on the provided keys.
   * @param keys An object representing the keys to filter the entries.
   * @returns FindBuilder
   * @example const results = await this.builder().find({ name : 'Customer 1', company : 'home' }).execute()
   *
   * */
  find<Keys extends Entry<T>>(keys: Entry<T>): FindBuilder<T, Keys>;

  /**
   * Finds entries based on the provided filters.
   * @param filter A Filter instance
   * @returns FindBuilder
   * @example
   * const filterLike = new Filter<Book>({
   *  field: 'currency_code',
   *  operator: 'LIKE',
   *  value: 'GBP',
   * });
   *
   * const results = await this.builder().find(filter).execute()
   *
   * */
  find<T>(filter: Filter<T>): FindBuilder<T, string>;

  /**
   * Finds a single entry based on the provided keys.
   * @param keys An object representing the keys to filter the entries.
   * @returns FindOneBuilder
   * @example const oneResult = await this.builder().findOne({ name : 'Customer 1', company : 'home' }).execute()
   *
   * */
  findOne<Keys extends Entry<T>>(keys: Entry<T>): FindOneBuilder<T, Keys>;

  /**
   * Finds a single entry based on the provided filters.
   * @param filter A Filter instance
   * @returns FindOneBuilder
   * @example
   * const filterLike = new Filter<Book>({
   *  field: 'currency_code',
   *  operator: 'LIKE',
   *  value: 'GBP',
   * });
   *
   * const oneResult = await this.builder().findOne(filter).execute()
   *
   * */
  findOne<T>(filter: Filter<T>): FindOneBuilder<T, string>;
};

// Start Filter types

type LogicalOperator = 'AND' | 'OR';

type FilterOperatorWhenNoValue = 'IS NULL' | 'IS NOT NULL';

type FilterOperatorWhenSingleValue =
  | 'EQUALS'
  | 'NOT EQUAL'
  | 'LIKE'
  | 'STARTS_WITH'
  | 'ENDS_WITH'
  | 'LESS THAN'
  | 'LESS THAN OR EQUALS'
  | 'GREATER THAN'
  | 'GREATER THAN OR EQUALS';
type FilterOperatorWhenTwoValues = 'BETWEEN' | 'NOT BETWEEN';
type FilterOperatorWhenArrayValues = 'IN' | 'NOT IN';

/**
 * Operators asserting the existence of an association : they are applied on an association
 * element (and not on a value) and are translated to the CQL `exists` / `not exists` predicates.
 */
type FilterOperatorWhenAssociation = 'EXISTS' | 'NOT EXISTS';

type FilterOperator =
  | FilterOperatorWhenSingleValue
  | FilterOperatorWhenTwoValues
  | FilterOperatorWhenArrayValues
  | FilterOperatorWhenNoValue
  | FilterOperatorWhenAssociation;

type FilterValue = string | number | null | boolean;

/**
 * Extracts the elements of `T` holding a value which a filter operator can be applied on.
 *
 * Everything is matched through its primitive type, which also keeps the key elements : the
 * `cds-typer` brands them as an intersection (`Key<number>` is `number & { ... }`) and the
 * date / time elements are generated as `string` types.
 */
type ValueKeys<T> = {
  [K in keyof T]-?: 0 extends 1 & T[K]
    ? never
    : NonNullable<T[K]> extends string | number | boolean | bigint
      ? K
      : never;
}[keyof T];

/**
 * Extracts the elements of `T` pointing to another entity : to-one associations (an object) and
 * to-many associations (an array of objects).
 *
 * Everything holding a value is left out : primitives, the primitive intersections branding the
 * key elements (`Key<number>` is `number & { ... }`), the streams behind the `LargeBinary`
 * elements, functions and the `Date` objects / binary buffers (`Uint8Array` also covers `Buffer`).
 *
 * Only ES lib types may be referenced here : a global from `@types/node` (E.g. `Buffer`) resolves
 * to an error type when the consumer has no Node typings loaded, which silently collapses this
 * type (and everything built on it, like `AssociationPath`) to `any`.
 *
 * The `0 extends 1 & T[K]` arm (here and in `ValueKeys`) drops the elements explicitly typed
 * `any` : a conditional on `any` takes both branches, so they would otherwise show up as
 * associations and leak `${string}` patterns into `AssociationPath`. An unresolvable element
 * type (E.g. the `import('stream').Readable` behind a `LargeBinary` element when the Node
 * typings are missing) cannot be guarded against : the checker's error type infects every
 * conditional touching it and collapses the union to `any`.
 */
type AssociationKeys<T> = {
  [K in keyof T]-?: 0 extends 1 & T[K]
    ? never
    : NonNullable<T[K]> extends string | number | boolean | bigint
      ? never
      : NonNullable<T[K]> extends Date | Uint8Array | ((...args: any[]) => any) | { pipe: (...args: any[]) => any }
        ? never
        : NonNullable<T[K]> extends object
          ? K
          : never;
}[keyof T];

/**
 * Extracts the elements of `T` pointing to a single entity (a non-array object), the only ones
 * which can be traversed with a path expression.
 */
type ToOneAssociationKeys<T> = {
  [K in AssociationKeys<T> & keyof T]: NonNullable<T[K]> extends readonly any[] ? never : K;
}[AssociationKeys<T> & keyof T];

/**
 * Resolves the entity behind an association element : the item type for a to-many association,
 * the object type itself for a to-one association.
 */
type AssociationTarget<Association> =
  NonNullable<Association> extends readonly (infer Item)[] ? Item : NonNullable<Association>;

/**
 * Dotted path expressions built from the to-one associations of `T` (E.g. `'author.name'`), the
 * leaf being a value element of the association target.
 *
 * Limited to a single hop on purpose, deeper paths would blow up on the circular entity types
 * generated by the `cds-typer`.
 */
type AssociationPath<T> = {
  [K in ToOneAssociationKeys<T> & keyof T & string]: `${K}.${Extract<ValueKeys<NonNullable<T[K]>>, string>}`;
}[ToOneAssociationKeys<T> & keyof T & string];

/**
 * Fields accepted by the value based filter operators : an element of `T` or a one-hop path
 * expression across a to-one association of `T`.
 */
type FilterField<T> = keyof T | AssociationPath<T>;

type FilterSingleValue = {
  operator: FilterOperatorWhenSingleValue;
  value: FilterValue;
};

type FilterBetween = {
  operator: FilterOperatorWhenTwoValues;
  value1: FilterValue;
  value2: FilterValue;
};

type FilterInAndNotIn = {
  operator: FilterOperatorWhenArrayValues;
  value: string[] | number[];
};

type FilterNoValue = {
  operator: FilterOperatorWhenNoValue;
};

/**
 * Filter options asserting the existence of an association of `T`.
 *
 * The `field` is restricted to the association elements of `T` and the optional `filters` is a
 * `Filter` typed on the entity behind that association, applied as an inner predicate
 * (E.g. `exists books[stock > 0]`). Omitting `filters` asserts the bare existence of the
 * association (E.g. `exists books`).
 */
type FilterExists<T> = {
  [K in AssociationKeys<T> & keyof T]: {
    field: K;
    operator: FilterOperatorWhenAssociation;
    filters?: Filter<AssociationTarget<T[K]>>;
  };
}[AssociationKeys<T> & keyof T];

type FilterOptions<T> =
  | ({
      field: FilterField<T>;
    } & (FilterSingleValue | FilterBetween | FilterInAndNotIn | FilterNoValue))
  | FilterExists<T>;

type CompoundFilter<T> = (Filter<T> | LogicalOperator | CompoundFilter<T>)[];

// End Filter types

// Start .columnsFormatter types

type NumericAggregateFunctions =
  | 'AVG'
  | 'MIN'
  | 'MAX'
  | 'SUM'
  | 'ABS'
  | 'CEILING'
  | 'TOTAL'
  | 'COUNT'
  | 'ROUND'
  | 'FLOOR';
type DateAggregateFunctions = 'DAY' | 'MONTH' | 'YEAR' | 'HOUR' | 'MINUTE' | 'SECOND';

type StringAggregateFunctions = 'LOWER' | 'UPPER' | 'LENGTH' | 'TRIM';
type StringAggregateTwoColumnsFunctions = 'CONCAT';

/**
 * Temporal difference functions (introduced in recent `@sap/cds` releases) that compute the
 * distance between two date/time columns. Native on `HANA` and emulated by other database
 * services (for example `@cap-js/sqlite`). Each returns a numeric difference.
 */
type TemporalTwoColumnsFunctions = 'DAYS_BETWEEN' | 'MONTHS_BETWEEN' | 'YEARS_BETWEEN' | 'SECONDS_BETWEEN';

type AggregateNumberUsingColumn = {
  aggregate?: NumericAggregateFunctions;
};

type AggregateDateUsingColumn = {
  aggregate?: DateAggregateFunctions;
};

type AggregateStringUsingColumn = {
  aggregate?: StringAggregateFunctions;
};

type AggregateStringTwoColumnsUsingColumn<T> = {
  aggregate?: StringAggregateTwoColumnsFunctions;
  column1: keyof T;
  column2: keyof T;
  renameAs: string;
};

type AggregateTemporalTwoColumnsUsingColumn<T> = {
  aggregate: TemporalTwoColumnsFunctions;
  column1: keyof T;
  column2: keyof T;
  renameAs: string;
};

type BaseAggregateFields<T> = {
  renameAs: string;
  column: keyof T;
};

type BuilderTypes = 'FIND_ONE' | 'FIND';

type AggregateFields<T, K = BuilderTypes> =
  | (BaseAggregateFields<T> &
      /* 
        If it's 'findOne' then remove the AggregateNumberUsingColumn as this works only when we have more than 1 entry in the table
        If it's 'find' this means the result will have more than 1 item and we can apply 'AVG', 'MAX', 'MIN' ... 
       **/
      (K extends 'FIND_ONE'
        ? AggregateStringUsingColumn | AggregateDateUsingColumn
        : AggregateStringUsingColumn | AggregateNumberUsingColumn | AggregateDateUsingColumn))
  | AggregateStringTwoColumnsUsingColumn<T>
  | AggregateTemporalTwoColumnsUsingColumn<T>;

type DynamicColumnTypes<T extends AggregateFields<K>[], K> = {
  [K in T[number]['renameAs']]: K extends Extract<
    T[number],
    { aggregate: NumericAggregateFunctions | DateAggregateFunctions | TemporalTwoColumnsFunctions }
  >['renameAs']
    ? number
    : K extends Extract<T[number], { aggregate: StringAggregateFunctions }>['renameAs']
      ? string
      : string; // Just renaming will get by default string
};

type ColumnFormatter<T, K = BuilderTypes> = AggregateFields<T, K>[];

type AddNewFields<T, K extends ColumnFormatter<T>> = T & Partial<DynamicColumnTypes<K, T>>;

type GetColumnNames<T, K extends ColumnFormatter<T>> = K[number][];

type AppendColumns<T, K extends ColumnFormatter<T>> = T & AddNewFields<T, GetColumnNames<T, K>>;

// End .columnsFormatter types

// Start deep expand of getExpand method

type Unpacked<T> = T extends (infer U)[]
  ? { expand?: Expand<U>; select?: (keyof U)[] }
  : { expand?: Expand<T>; select?: (keyof T)[] };

type AutoExpandLevels = { levels?: number };

type Expand<T> = {
  [P in keyof T]: Unpacked<T[P]>;
} & AutoExpandLevels;

type ExpandStructure = Record<string, any>;

type ValueExpand = {
  select: any[];
  expand: ExpandStructure;
};

// End deep expand of getExpand method

// Start increment/decrement types

/**
 * Extracts only the numeric keys from a type.
 * Used for increment/decrement operations which only work on numeric fields.
 */
type NumericKeys<T> = {
  [K in keyof T]: T[K] extends number | null | undefined ? K : never;
}[keyof T];

/**
 * Creates a partial type with only numeric fields for increment/decrement operations.
 */
type IncrementFields<T> = Partial<Record<NumericKeys<T>, number>>;

// End increment/decrement types

// Start .executeAndCount types

/**
 * Result of `.executeAndCount()` : the rows of the query (paginated when `.paginate()` was used)
 * together with the total number of rows matching the query, ignoring the pagination.
 */
type ExecuteAndCountResult<T> = {
  results: T[];
  count: number;
};

// End .executeAndCount types

export type {
  // Common
  ExternalServiceProps,
  BaseRepositoryConstructor,
  ExtractSingular,
  Entry,
  Draft,
  EntryDraft,
  Locale,
  InsertResult,
  DraftAdministrativeFields,
  Request,
  Columns,
  ShowOnlyColumns,
  Entries,
  DraftEntries,
  AssociationFunction,
  Entity,
  AutoExpandLevels,

  // Builder types
  FindReturn,
  FilterValue,
  LogicalOperator,
  FilterOperator,
  FilterOptions,
  FilterField,
  Expand,
  ValueExpand,
  ExpandStructure,
  CompoundFilter,
  ExecuteAndCountResult,

  // ColumnsFormatter types
  ColumnFormatter,
  AddNewFields,
  GetColumnNames,
  AppendColumns,
  DynamicColumnTypes,
  NumericAggregateFunctions,
  DateAggregateFunctions,
  StringAggregateFunctions,
  StringAggregateTwoColumnsFunctions,
  TemporalTwoColumnsFunctions,

  // Increment/Decrement types
  NumericKeys,
  IncrementFields,
};
