name: Deployment

on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  contents: write
  pull-requests: write

jobs:
  # This will validate to see if the labels contains 'none' which means that if 'none' was found the release will not happen
  check_valid_deploy:
    name: Validate deploy conditions
    if: ${{ contains(github.event.pull_request.labels.*.name, 'deploy') }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Proceed valid"

    # This will start build of the project
  check_valid_build:
    name: Check build validity
    runs-on: ubuntu-latest
    needs: [check_valid_deploy]
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run build

  # This will push the latest build of the project to npm
  publish-npm:
    name: Publish to npm public
    needs: check_valid_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
      - run: npm run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
