# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  # This will start unit/integration testing
  test-unit:
    name: Unit
    runs-on: macos-latest

    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Start unit / integration tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: test-unit
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - run: npm install
      - run: npm run build

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - run: npm install
      - run: npm run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
