# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.

name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '36 18 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-issue-stale: 30
          stale-issue-message: 'This issue has not been updated in a while. If it is still relevant, please comment on it to keep it open. The issue will be closed soon if it remains inactive.'
          close-issue-message: 'This issue has been closed automatically due to inactivity.'
          stale-pr-message: 'This PR has not been updated in a while. If it is still relevant, please comment on it to keep it open. The PR will be closed soon if it remains inactive.'
          close-pr-message: 'This PR has been closed automatically due to inactivity.'
          stale-issue-label: 'status: stale'
          stale-pr-label: 'status: stale'
          exempt-issue-labels: 'type: feature request'
          exempt-pr-labels: 'type: feature request'
          exempt-all-milestones: true
