# This will run unit / integration and e2e tests

name: Test

on:
  pull_request:
    types: [opened, edited, synchronize]

  workflow_dispatch:

jobs:
  # This will start unit/integration testing
  test-unit:
    name: Unit
    runs-on: macos-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install -g ts-node @sap/cds-dk typescript

      - name: Install dependencies
        run: npm install

      - name: Start unit / integration tests
        run: npm test

  # This will start e2e testing
  test-e2e:
    name: e2e
    runs-on: macos-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install -g ts-node @sap/cds-dk typescript

      - name: Install dependencies
        run: npm install

      - name: Start e2e tests
        run: npm run test:e2e